spring:
  profiles:
    active: dev

---
spring:
  profiles: dev #开发环境
  application:
    name: gitHub-config-dev
server: 
  port: 1111

---
spring:
  profiles: test #测试环境
  application:
    name: gitHub-config-test
server: 
  port: 2222
