spring:
  profiles:
    active: dev

---
spring:
  profiles: dev #开发环境
  application:
    name: ms-config-dev
server: 
  port: 2222

---
spring:
  profiles: test #测试环境
  application:
    name: ms-config-test
server: 
  port: 4444
