spring:
  profiles:
    active: dev

---
server:
  port: 3355

spring:
  profiles: dev #开发环境
  application:
    name: ms-config-client

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
       defaultZone: http://www.Eureka7001.com:7001/eureka

---
server:
  port: 3366

spring:
  profiles: test #测试环境
  application:
    name: ms-config-client

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
       defaultZone: http://www.Eureka7001.com:7001/eureka